// Mock data for Alloy Client Portal
export const DATA = {
  user: { name: 'Marcus Avery', initials: 'MA', role: 'owner' },
  account: {
    company: 'RISE Association Management Group',
    tier: 'Accelerate',
    market: 'Austin–Round Rock TX',
    since: 'Mar 2025',
  },
  roles: [
    { id: 'owner', label: 'Owner' },
    { id: 'bd', label: 'BD' },
    { id: 'ops', label: 'Ops' },
  ],
  kpis: [
    {
      label: 'Boards signed (12 mo)',
      value: '9',
      trend: '+3',
      up: true,
      icon: 'trophy',
      tone: 'pink',
    },
    {
      label: 'Qualified opportunities',
      value: '412',
      trend: '+38%',
      up: true,
      icon: 'phone',
      tone: 'yellow',
    },
    {
      label: 'Investment ratio',
      value: '7.3×',
      trend: '+1.4×',
      up: true,
      icon: 'trend',
      tone: 'purple',
    },
    {
      label: 'Avg review rating',
      value: '4.8',
      trend: '+0.2',
      up: true,
      icon: 'star',
      tone: 'green',
    },
  ],
  projects: [
    {
      id: 'PR-218',
      title: 'Geo landing pages — North Austin cluster',
      phase: 'BoardReach',
      pct: 72,
      status: 'in-progress',
      due: 'Apr 12',
      dueRel: 'in 26 days',
      owners: ['JG', 'SN'],
      pulse: 'Last update 2h ago',
    },
    {
      id: 'PR-201',
      title: 'Proposal redesign v2 — Premium kit',
      phase: 'BoardMatch',
      pct: 88,
      status: 'review',
      due: 'Mar 21',
      dueRel: 'in 4 days',
      owners: ['CL'],
      pulse: 'Awaiting your approval',
    },
    {
      id: 'PR-194',
      title: 'Outsmarting AI Search · micro-course',
      phase: 'Energy',
      pct: 100,
      status: 'live',
      due: 'Mar 14',
      dueRel: 'shipped',
      owners: ['JG', 'SN', 'CL'],
      pulse: 'Live · 247 views',
    },
    {
      id: 'PR-225',
      title: 'Q1 board education program — Module 3',
      phase: 'BoardRetain',
      pct: 34,
      status: 'in-progress',
      due: 'Apr 28',
      dueRel: 'in 6 wks',
      owners: ['SN', 'CL'],
      pulse: 'Drafting outline',
    },
    {
      id: 'PR-211',
      title: 'GBP listings refresh — all 3 locations',
      phase: 'BoardReach',
      pct: 18,
      status: 'blocked',
      due: 'Apr 4',
      dueRel: 'blocked',
      owners: ['JG'],
      pulse: 'Need photos from you',
    },
    {
      id: 'PR-188',
      title: 'RISE case study — Lakeway Villas signing',
      phase: 'BoardReach',
      pct: 100,
      status: 'live',
      due: 'Feb 22',
      dueRel: 'shipped',
      owners: ['CL', 'SN'],
      pulse: 'Live · 1.4K views',
    },
  ],
  recentLeads: [
    {
      name: 'Westwind HOA · Karen Maslo',
      source: "Google Ads · 'hoa management austin'",
      quality: 'qualified',
      value: '$48K/yr',
      time: '12 min ago',
      type: 'call',
    },
    {
      name: 'Cedar Park Townhomes',
      source: 'Organic · /services/board-management',
      quality: 'hot',
      value: '$72K/yr',
      time: '1h ago',
      type: 'form',
    },
    {
      name: 'Riverstone Master Assoc.',
      source: 'GBP · Round Rock listing',
      quality: 'review',
      value: '$110K/yr',
      time: '3h ago',
      type: 'call',
    },
    {
      name: 'Brushy Creek Community',
      source: 'Direct · referral form',
      quality: 'qualified',
      value: '$58K/yr',
      time: 'yesterday',
      type: 'form',
    },
  ],
  activity: [
    {
      color: 'pink',
      text: 'Lakeway Villas signed — $54K/yr contract attributed to Alloy',
      meta: 'Just now · BoardMatch · +1 badge unlocked',
    },
    {
      color: 'yellow',
      text: '12 new qualified leads from your Google Ads campaign',
      meta: '1h ago · WhatConverts',
    },
    {
      color: 'blue',
      text: 'Justin sent the new proposal v2 for your review',
      meta: '3h ago · BoardMatch · 2 changes',
    },
    {
      color: 'green',
      text: 'Your Google review average climbed to 4.8★ (+0.2)',
      meta: 'Yesterday · BoardRetain',
    },
    {
      color: 'purple',
      text: 'Q1 strategy session notes published',
      meta: 'Mar 12 · 14 priorities tracked',
    },
  ],
  tickets: [
    {
      id: 'ZD-4218',
      title: 'Update phone number on every site footer',
      priority: 'med',
      status: 'open',
      agent: 'Cameron Lange',
      time: '12 min ago',
      excerpt:
        'Hi team — we just changed our main 800 number to 855-555-0144. Can you push it everywhere it shows on our site, including the GBP listings, footer, and contact page?',
    },
    {
      id: 'ZD-4209',
      title: 'Need a quick edit on the Westwind case study',
      priority: 'low',
      status: 'in-progress',
      agent: 'Skyler Nelson',
      time: '2h ago',
      excerpt: 'Board chair sent over a corrected quote — can we swap it on the case study page?',
    },
    {
      id: 'ZD-4187',
      title: 'Question on Q2 budget — adding board education?',
      priority: 'high',
      status: 'open',
      agent: 'Justin Guenther',
      time: 'Yesterday',
      excerpt:
        'Want to talk through whether we have point budget room to add a 4-module board education program in Q2.',
    },
    {
      id: 'ZD-4156',
      title: 'Feedback on proposal v2 design',
      priority: 'med',
      status: 'answered',
      agent: 'Cameron Lange',
      time: '3 days ago',
      excerpt: 'Loved the new layout — one note on the cover page typography.',
    },
    {
      id: 'ZD-4144',
      title: 'Send tradeshow assets for CAI Austin chapter',
      priority: 'med',
      status: 'answered',
      agent: 'Justin Guenther',
      time: 'Last week',
      excerpt: 'Need the booth banner and table topper files by Friday for the printer.',
    },
  ],
  roadmap: [
    {
      q: 'Q3 2025',
      title: 'Foundation',
      state: 'done',
      items: [
        { lane: 'attract', t: 'Site audit + technical SEO', kind: '✓' },
        { lane: 'attract', t: 'GA4 + WhatConverts wired', kind: '✓' },
        { lane: 'attract', t: 'Keyword research', kind: '✓' },
        { lane: 'close', t: 'Sales messaging refresh', kind: '✓' },
      ],
    },
    {
      q: 'Q4 2025',
      title: 'Authority',
      state: 'done',
      items: [
        { lane: 'attract', t: 'Geo cluster: South Austin (12 pages)', kind: '✓' },
        { lane: 'attract', t: 'Outsmarting AI Search course', kind: '✓' },
        { lane: 'close', t: 'Proposal redesign v1', kind: '✓' },
        { lane: 'keep', t: 'Review generation campaign', kind: '✓' },
      ],
    },
    {
      q: 'Q1 2026',
      title: 'Momentum',
      state: 'now',
      items: [
        { lane: 'attract', t: 'Geo cluster: North Austin', kind: '●' },
        { lane: 'attract', t: 'GBP refresh — 3 locations', kind: '◐' },
        { lane: 'close', t: 'Premium proposal kit v2', kind: '●' },
        { lane: 'keep', t: 'Board education · Module 3', kind: '●' },
      ],
    },
    {
      q: 'Q2 2026',
      title: 'Scale',
      state: 'next',
      items: [
        { lane: 'attract', t: 'Pillar: HOA budgeting authority hub', kind: '○' },
        { lane: 'attract', t: 'Round Rock geo cluster', kind: '○' },
        { lane: 'close', t: 'BD training · 2 sessions', kind: '○' },
        { lane: 'keep', t: 'Onboarding system v1', kind: '○' },
      ],
    },
    {
      q: 'Q3+ 2026',
      title: 'Expansion',
      state: 'future',
      items: [
        { lane: 'energy', t: 'Certification track design', kind: '○' },
        { lane: 'attract', t: 'Consider second metro market', kind: '○' },
        { lane: 'close', t: 'RFP system templates', kind: '○' },
      ],
    },
  ],
  badges: [
    {
      id: 'first-board',
      name: 'First Board',
      desc: 'Signed your first contract attributed to Alloy.',
      state: 'earned',
      earned: 'Earned May 2025',
      color: 'pink',
      category: 'milestone',
    },
    {
      id: 'five-wins',
      name: 'Five Wins',
      desc: '5 boards signed through the Alloy growth engine.',
      state: 'earned',
      earned: 'Earned Nov 2025',
      color: 'pink',
      category: 'milestone',
    },
    {
      id: '100k-pipeline',
      name: '$100K Pipeline',
      desc: 'Crossed $100K in attributed contract value.',
      state: 'earned',
      earned: 'Earned Jul 2025',
      color: 'yellow',
      category: 'pipeline',
    },
    {
      id: '500k-pipeline',
      name: 'Half-Mil Mark',
      desc: 'Crossed $500K in lifetime attributed value.',
      state: 'earned',
      earned: 'Earned Feb 2026',
      color: 'yellow',
      category: 'pipeline',
    },
    {
      id: 'review-streak',
      name: 'Review Magnet',
      desc: 'Maintained 4.5★+ average across 100+ reviews.',
      state: 'earned',
      earned: 'Earned Jan 2026',
      color: 'green',
      category: 'health',
    },
    {
      id: 'engagement-30',
      name: '30-Day Streak',
      desc: 'Logged into the portal 30 days running.',
      state: 'earned',
      earned: 'Earned today 🔥',
      color: 'blue',
      category: 'engagement',
    },
    {
      id: 'authority-tier',
      name: 'Authority Tier',
      desc: 'Unlocked Authority status with 2+ published courses.',
      state: 'earned',
      earned: 'Earned Mar 2026',
      color: 'purple',
      category: 'tier',
    },
    {
      id: 'ten-wins',
      name: 'Ten Wins',
      desc: '10 boards signed — graduate to elite client status.',
      state: 'progress',
      pct: 90,
      color: 'pink',
      category: 'milestone',
    },
    {
      id: 'geo-titan',
      name: 'Geo Titan',
      desc: 'Top-3 ranking in 3 distinct geo markets.',
      state: 'progress',
      pct: 60,
      color: 'yellow',
      category: 'visibility',
    },
    {
      id: 'no-churn',
      name: "Zero Churn '26",
      desc: 'Make it through the calendar year with no association loss.',
      state: 'progress',
      pct: 22,
      color: 'green',
      category: 'health',
    },
    {
      id: 'million-pipeline',
      name: '$1M Mark',
      desc: 'Cross $1M in lifetime Alloy-attributed value.',
      state: 'locked',
      color: 'yellow',
      category: 'pipeline',
    },
    {
      id: 'ascend',
      name: 'Ascend Tier',
      desc: 'Graduate to the Ascend tier — multi-market expansion.',
      state: 'locked',
      color: 'purple',
      category: 'tier',
    },
    {
      id: 'founders-day',
      name: "Founders' Day",
      desc: 'Spend a full strategy day with the Alloy partners in Austin.',
      state: 'locked',
      color: 'pink',
      category: 'reward',
    },
  ],
  roi: {
    yearLabel: 'Mar 2025 – Mar 2026',
    invested: 84000,
    contractValue: 612000,
    boardsSigned: 9,
    ratio: 7.3,
    rankingsTracked: 142,
    rankingsTop10: 47,
  },
  library: [
    {
      lane: 'attract',
      stage: 'BoardReach',
      ttl: 'The CAM SEO Field Guide',
      meta: 'Guide · 24 min read',
      desc: 'Everything you need to outrank generalist competitors in your metro.',
    },
    {
      lane: 'attract',
      stage: 'BoardReach',
      ttl: 'Outsmarting AI Search',
      meta: 'Course · 5 lessons · in progress',
      desc: 'How micro-courses drive citations from Perplexity, Gemini & ChatGPT.',
    },
    {
      lane: 'close',
      stage: 'BoardMatch',
      ttl: 'Proposal Anatomy',
      meta: 'Playbook · 14 sections',
      desc: 'What separates a winning CAM proposal from a discarded PDF.',
    },
    {
      lane: 'close',
      stage: 'BoardMatch',
      ttl: 'Discovery Frameworks for BD',
      meta: 'Training · 3 sessions',
      desc: 'The conversation pattern that gets boards talking honestly.',
    },
    {
      lane: 'keep',
      stage: 'BoardRetain',
      ttl: 'Manager Transition Playbook',
      meta: 'Guide · 16 min read',
      desc: 'Save the association when your manager moves on.',
    },
    {
      lane: 'keep',
      stage: 'BoardRetain',
      ttl: 'Board Education · Governance 101',
      meta: 'Course · 6 modules',
      desc: 'Position your firm as the educator. Reduce churn from misunderstanding.',
    },
    {
      lane: 'energy',
      stage: 'L&D',
      ttl: 'Building a Staff Onboarding Engine',
      meta: 'Toolkit · templates included',
      desc: 'Cut time-to-productivity for new community managers in half.',
    },
    {
      lane: 'energy',
      stage: 'L&D',
      ttl: 'Gamification for CAM Staff',
      meta: 'Strategy guide · 18 min read',
      desc: 'How recognition systems lift retention without feeling corny.',
    },
  ],
};
